resources:
  - name: website_snapshot
    type: GitRepo
    configuration:
      gitProvider: github_wakingrufus
      path: wakingrufus/website
      branches:
        include: master
      buildOn:
        commit: true
      cancelPendingRunsOn:
        newCommit: true
        pullRequestUpdate: true
  - name: website_pull_request
    type: GitRepo
    configuration:
      gitProvider: github_wakingrufus
      path: wakingrufus/website
      buildOn:
        commit: false
        pullRequestCreate: true
      cancelPendingRunsOn:
        newCommit: true
        pullRequestUpdate: true
  - name: website_release
    type: GitRepo
    configuration:
      gitProvider: github_wakingrufus
      path: wakingrufus/website
      buildOn:
        commit: false
        tagCreate: true
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrog

pipelines:
  - name: website_snapshot
    steps:
      - name: build
        type: GradleBuild
        configuration:
          gradleCommand: "build"
          useWrapper: true
          autoPublishBuildInfo: true
          usesPlugin: true
          inputResources:
            - name: website_snapshot
          outputResources:
            - name: build_info
          integrations:
            - name: jfrog
        execution:
          onStart:
            - echo "Preparing for work..."
            - update_commit_status website_snapshot --message "starting..." --context "$step_name"
          onSuccess:
            - echo "Job well done!"
            - update_commit_status website_snapshot --message "Succeeded" --context "$step_name"
          onFailure:
            - echo "uh oh, something went wrong"
            - update_commit_status website_snapshot --message "Failed!" --context "$step_name"
          onComplete: #always
            - echo "Cleaning up some stuff"
  - name: website_build
    steps:
      - name: build
        type: GradleBuild
        configuration:
          gradleCommand: "build"
          useWrapper: true
          autoPublishBuildInfo: true
          usesPlugin: true
          inputResources:
            - name: website_pull_request
          outputResources:
            - name: build_info
          integrations:
            - name: jfrog
        execution:
          onStart:
            - echo "Preparing for work..."
            - update_commit_status website_pull_request --message "starting..." --context "$step_name"
          onSuccess:
            - echo "Job well done!"
            - update_commit_status website_pull_request --message "Succeeded" --context "$step_name"
          onFailure:
            - echo "uh oh, something went wrong"
            - update_commit_status website_pull_request --message "Failed!" --context "$step_name"
          onComplete: #always
            - echo "Cleaning up some stuff"
  - name: website_release
    configuration:
    steps:
      - name: build
        type: GradleBuild
        configuration:
          gradleCommand: "artifactoryPublish"
          useWrapper: true
          autoPublishBuildInfo: true
          usesPlugin: true
          inputResources:
            - name: website_release
          outputResources:
            - name: build_info
          integrations:
            - name: jfrog
        execution:
          onStart:
            - echo "Preparing for work..."
            - update_commit_status website_release --message "starting..." --context "$step_name"
          onSuccess:
            - echo "Job well done!"
            - update_commit_status website_release --message "Succeeded" --context "$step_name"
          onFailure:
            - echo "uh oh, something went wrong"
            - update_commit_status website_release --message "Failed!" --context "$step_name"
          onComplete: #always
            - echo "Cleaning up some stuff"